version: "3.8"

networks:
  cinema-network:
    name: cinema-network
    driver: bridge

services:
  cinema-api:
    build:
      context: ./backend/cinema_booking_api
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - cinema-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
  
  cinema-frontend:
    build:
      context: ./frontend/cinema_booking_app
      dockerfile: Dockerfile
    networks:
        - cinema-network
    ports:
      - "3000:3000"
    expose:
      - "3000"